In [1]:
import pandas as pd

In [2]:
df1 = pd.DataFrame({'name':['vicky', 'micky'], 'age':[34,45]})
df2 = pd.DataFrame({'name':['steve', 'jobs'], 'age':[45,55]})

In [3]:
df1

    name  age
0  vicky   34
1  micky   45

In [4]:
df2

    name  age
0  steve   45
1   jobs   55

In [5]:
# concate
pd.concat([df1,df2], axis = 1)

    name  age   name  age
0  vicky   34  steve   45
1  micky   45   jobs   55

In [7]:
df3 = pd.concat([df1,df2], axis = 0)

In [8]:
df3

    name  age
0  vicky   34
1  micky   45
0  steve   45
1   jobs   55

In [9]:
df4 = pd.DataFrame({'name':['pinky', 'kamal'], 'age':[34,40], 'hobby':['reading','swimming']})
df4

    name  age     hobby
0  pinky   34   reading
1  kamal   40  swimming

In [10]:
pd.concat([df3,df4], join = 'outer', ignore_index=True)

    name  age     hobby
0  vicky   34       NaN
1  micky   45       NaN
2  steve   45       NaN
3   jobs   55       NaN
4  pinky   34   reading
5  kamal   40  swimming

In [11]:
pd.concat([df3,df4], join = 'inner', ignore_index=True)

    name  age
0  vicky   34
1  micky   45
2  steve   45
3   jobs   55
4  pinky   34
5  kamal   40

merge

In [12]:
size = pd.DataFrame({'color':['red','green','blue'],'size' :['M','S','XL']})
gender = pd.DataFrame({'color':['red','green','pink'],'gender' :['M','F','M']})

In [13]:
size

   color size
0    red    M
1  green    S
2   blue   XL

In [14]:
gender

   color gender
0    red      M
1  green      F
2   pink      M

In [15]:
pd.merge(size,gender, how = 'outer')

   color size gender
0   blue   XL    NaN
1  green    S      F
2   pink  NaN      M
3    red    M      M

In [16]:
pd.merge(size,gender, how = 'inner')

   color size gender
0    red    M      M
1  green    S      F

In [17]:
pd.merge(size,gender, how = 'left')

   color size gender
0    red    M      M
1  green    S      F
2   blue   XL    NaN

In [18]:
pd.merge(size,gender, how = 'right')

   color size gender
0    red    M      M
1  green    S      F
2   pink  NaN      M