In [1]:
import pandas as pd
my_list = [1,2,3,4,5]

In [2]:
pd.Series(data = my_list)

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [3]:
tu = ('a', 'b', 'c', 'd', 'e')
pd.Series(data = tu)

0    a
1    b
2    c
3    d
4    e
dtype: object

In [4]:
pd.Series(data = my_list, index = tu)

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [5]:
pd.Series(data = tu, index = my_list)

1    a
2    b
3    c
4    d
5    e
dtype: object

In [6]:
lis_2 = [1,1,1,1,1]
pd.Series(tu, lis_2)

1    a
1    b
1    c
1    d
1    e
dtype: object

In [7]:
dic = {'a':'apple', 'b':'banana', 'c':'coffee'}
pd.Series(dic)

a     apple
b    banana
c    coffee
dtype: object

In [8]:
S1 = pd.Series([1,2,3,4], index = ['USA','UAE','SDE','ITALY'])
S1

USA      1
UAE      2
SDE      3
ITALY    4
dtype: int64

In [9]:
S2 = pd.Series([1,5,3,4], index = ['USA','India','SDE','ITALY'])
S2

USA      1
India    5
SDE      3
ITALY    4
dtype: int64

In [10]:
S1+S2

ITALY    8.0
India    NaN
SDE      6.0
UAE      NaN
USA      2.0
dtype: float64

In [11]:
S1+S1

USA      2
UAE      4
SDE      6
ITALY    8
dtype: int64

In [12]:
import numpy as np
from numpy.random import randn

# randn (+,-,float)
# rand (0,1)
# randint (integer)

In [14]:
np.random.seed(101)
df = pd.DataFrame(data = randn(5,4), index = ['A','B','C','D','E'], columns = ['W','X','Y','Z'])
df

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [15]:
df['W']

A    2.706850
B    0.651118
C   -2.018168
D    0.188695
E    0.190794
Name: W, dtype: float64

In [16]:
type(df['W'])

pandas.core.series.Series

In [17]:
df[['X','Y']] # pass as list as if it has more than one column/ series

          X         Y
A  0.628133  0.907969
B -0.319318 -0.848077
C  0.740122  0.528813
D -0.758872 -0.933237
E  1.978757  2.605967

In [18]:
df

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [20]:
# added new column
#df['new'] = [1,2,3,4,5] # opt 1
df['new'] = df['W'] + df['X'] # opt 2
df # new df updated with new col

          W         X         Y         Z       new
A  2.706850  0.628133  0.907969  0.503826  3.334983
B  0.651118 -0.319318 -0.848077  0.605965  0.331800
C -2.018168  0.740122  0.528813 -0.589001 -1.278046
D  0.188695 -0.758872 -0.933237  0.955057 -0.570177
E  0.190794  1.978757  2.605967  0.683509  2.169552

In [21]:
# delet one colum
df.drop('new', axis = 1) # axis = 0 => row

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [22]:
df

          W         X         Y         Z       new
A  2.706850  0.628133  0.907969  0.503826  3.334983
B  0.651118 -0.319318 -0.848077  0.605965  0.331800
C -2.018168  0.740122  0.528813 -0.589001 -1.278046
D  0.188695 -0.758872 -0.933237  0.955057 -0.570177
E  0.190794  1.978757  2.605967  0.683509  2.169552

In [23]:
df.drop('new', axis = 1, inplace = True)
df

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [24]:
# delete row

df.drop('C', axis =0)

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [25]:
df

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [26]:
df.drop('C', axis =0, inplace = True)

In [27]:
df

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [28]:
df.loc['D']   # label based access of row

W    0.188695
X   -0.758872
Y   -0.933237
Z    0.955057
Name: D, dtype: float64

In [29]:
df.loc[['A', 'D']]

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
D  0.188695 -0.758872 -0.933237  0.955057

In [30]:
# index based access of row

df.iloc[0]

W    2.706850
X    0.628133
Y    0.907969
Z    0.503826
Name: A, dtype: float64

In [31]:
df.iloc[[0,2]]

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
D  0.188695 -0.758872 -0.933237  0.955057

In [32]:
df.loc[['A','D'],['W', 'Y']]

          W         Y
A  2.706850  0.907969
D  0.188695 -0.933237

In [34]:
df.iloc[[0,2],[0,2]]

          W         Y
A  2.706850  0.907969
D  0.188695 -0.933237

In [35]:
df

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [36]:
df_2 = pd.DataFrame(data = randn(5,4), index = ['A','B','C','D','E'], columns = ['W','X','Y','Z'])
df_2

          W         X         Y         Z
A  0.302665  1.693723 -1.706086 -1.159119
B -0.134841  0.390528  0.166905  0.184502
C  0.807706  0.072960  0.638787  0.329646
D -0.497104 -0.754070 -0.943406  0.484752
E -0.116773  1.901755  0.238127  1.996652

In [37]:
df_2['new'] = ['AA','BB','CC','DD','EE']

In [39]:
df_2

          W         X         Y         Z new
A  0.302665  1.693723 -1.706086 -1.159119  AA
B -0.134841  0.390528  0.166905  0.184502  BB
C  0.807706  0.072960  0.638787  0.329646  CC
D -0.497104 -0.754070 -0.943406  0.484752  DD
E -0.116773  1.901755  0.238127  1.996652  EE

In [40]:
df_2.reset_index()

  index         W         X         Y         Z new
0     A  0.302665  1.693723 -1.706086 -1.159119  AA
1     B -0.134841  0.390528  0.166905  0.184502  BB
2     C  0.807706  0.072960  0.638787  0.329646  CC
3     D -0.497104 -0.754070 -0.943406  0.484752  DD
4     E -0.116773  1.901755  0.238127  1.996652  EE

In [41]:
df_2.set_index('new')

            W         X         Y         Z
new
AA   0.302665  1.693723 -1.706086 -1.159119
BB  -0.134841  0.390528  0.166905  0.184502
CC   0.807706  0.072960  0.638787  0.329646
DD  -0.497104 -0.754070 -0.943406  0.484752
EE  -0.116773  1.901755  0.238127  1.996652

In [42]:
df_2['new_1'] = ['tt','yy','uu','ii','oo']

In [43]:
df_2.set_index('new_1')

              W         X         Y         Z new
new_1
tt     0.302665  1.693723 -1.706086 -1.159119  AA
yy    -0.134841  0.390528  0.166905  0.184502  BB
uu     0.807706  0.072960  0.638787  0.329646  CC
ii    -0.497104 -0.754070 -0.943406  0.484752  DD
oo    -0.116773  1.901755  0.238127  1.996652  EE

In [44]:
df_2.reset_index()

  index         W         X         Y         Z new new_1
0     A  0.302665  1.693723 -1.706086 -1.159119  AA    tt
1     B -0.134841  0.390528  0.166905  0.184502  BB    yy
2     C  0.807706  0.072960  0.638787  0.329646  CC    uu
3     D -0.497104 -0.754070 -0.943406  0.484752  DD    ii
4     E -0.116773  1.901755  0.238127  1.996652  EE    oo