In [1]:
import pandas as pd

In [2]:
dataset = pd.read_csv('gun-violence-data1.csv') 
dataset.head()

,incident_id,date,state,city_or_county,address,n_killed,n_injured
0,461105,01-01-2013,Pennsylvania,Mckeesport,1506 Versailles Avenue and Coursin Street,0,4
1,460726,01-01-2013,California,Hawthorne,13500 block of Cerise Avenue,1,3
2,478855,01-01-2013,Ohio,Lorain,1776 East 28th Street,1,3
3,478925,05-01-2013,Colorado,Aurora,16000 block of East Ithaca Place,4,0
4,478959,07-01-2013,North Carolina,Greensboro,307 Mourning Dove Terrace,2,2

In [3]:
dataset.drop(columns = ['incident_id','city_or_county','address'], inplace = True)
dataset.head()

         date           state  n_killed  n_injured
0  01-01-2013    Pennsylvania         0          4
1  01-01-2013      California         1          3
2  01-01-2013            Ohio         1          3
3  05-01-2013        Colorado         4          0
4  07-01-2013  North Carolina         2          2

In [4]:
from datetime import datetime

#dataset['date'] = pd.to_datetime(dataset['date'], format = '%m-%d-%Y') # covert date into datetime formate
dataset['date'] = pd.to_datetime(dataset['date'], dayfirst=True) # covert date into datetime formate
dataset['year'] = dataset['date'].dt.year
dataset['month']= dataset['date'].dt.month
dataset['day']= dataset['date'].dt.day
dataset['day_of_week']= dataset['date'].dt.dayofweek

dataset['tot_victim'] = dataset['n_killed'] + dataset['n_injured']

dataset.head()

,date,state,n_killed,n_injured,year,month,day,day_of_week,tot_victim
0,2013-01-01,Pennsylvania,0,4,2013,1,1,1,4
1,2013-01-01,California,1,3,2013,1,1,1,4
2,2013-01-01,Ohio,1,3,2013,1,1,1,4
3,2013-01-05,Colorado,4,0,2013,1,5,5,4
4,2013-01-07,North Carolina,2,2,2013,1,7,0,4

In [5]:
dataset['day_of_week'] = dataset['day_of_week'].map({0:'Monday',1:'Tue',2:'Wed',3:'Thurs',4:'Friday',5:'Satur',6:'Sunday'})
dataset.head()

,date,state,n_killed,n_injured,year,month,day,day_of_week,tot_victim
0,2013-01-01,Pennsylvania,0,4,2013,1,1,Tue,4
1,2013-01-01,California,1,3,2013,1,1,Tue,4
2,2013-01-01,Ohio,1,3,2013,1,1,Tue,4
3,2013-01-05,Colorado,4,0,2013,1,5,Satur,4
4,2013-01-07,North Carolina,2,2,2013,1,7,Monday,4

In [6]:
dataset.isnull().sum()

date           0
state          0
n_killed       0
n_injured      0
year           0
month          0
day            0
day_of_week    0
tot_victim     0
dtype: int64

Groupwise

In [7]:
dataset['day_of_week'].value_counts()

day_of_week
Sunday    37052
Satur     36096
Wed       34126
Monday    33760
Tue       33307
Friday    32775
Thurs     32561
Name: count, dtype: int64

In [8]:
dataset.groupby('day_of_week')['tot_victim'].count()

day_of_week
Friday    32775
Monday    33760
Satur     36096
Sunday    37052
Thurs     32561
Tue       33307
Wed       34126
Name: tot_victim, dtype: int64

In [9]:
dataset.groupby('state')['tot_victim'].sum()

state
Alabama                  4878
Alaska                    592
Arizona                  2190
Arkansas                 2120
California              13206
Colorado                 1929
Connecticut              1599
Delaware                 1070
District of Columbia     1874
Florida                 10981
Georgia                  6512
Hawaii                    148
Idaho                     315
Illinois                16923
Indiana                  4564
Iowa                     1094
Kansas                   1473
Kentucky                 2960
Louisiana                6577
Maine                     244
Maryland                 4858
Massachusetts            2173
Michigan                 4578
Minnesota                1377
Mississippi              3059
Missouri                 5721
Montana                   290
Nebraska                  899
Nevada                   1750
New Hampshire             232
New Jersey               3708
New Mexico               1038
New York                 6764
North Carolina           6854
North Dakota              199
Ohio                     8211
Oklahoma                 2491
Oregon                   1140
Pennsylvania             7451
Rhode Island              409
South Carolina           4694
South Dakota              204
Tennessee                6302
Texas                   11152
Utah                      684
Vermont                   130
Virginia                 5025
Washington               2140
West Virginia             984
Wisconsin                2979
Wyoming                   125
Name: tot_victim, dtype: int64

In [10]:
import numpy as np
dataset.groupby('month')['tot_victim'].agg([np.mean, min, max])

C:\Users\ajant\AppData\Local\Temp\ipykernel_2332\812552987.py:2: FutureWarning: The provided callable <function mean at 0x0000020DBB5C3F60> is currently using SeriesGroupBy.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.
  dataset.groupby('month')['tot_victim'].agg([np.mean, min, max])
C:\Users\ajant\AppData\Local\Temp\ipykernel_2332\812552987.py:2: FutureWarning: The provided callable <built-in function min> is currently using SeriesGroupBy.min. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "min" instead.
  dataset.groupby('month')['tot_victim'].agg([np.mean, min, max])
C:\Users\ajant\AppData\Local\Temp\ipykernel_2332\812552987.py:2: FutureWarning: The provided callable <built-in function max> is currently using SeriesGroupBy.max. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "max" instead.
  dataset.groupby('month')['tot_victim'].agg([np.mean, min, max])

           mean  min  max
month
1      0.735395    0   16
2      0.709357    0   34
3      0.711837    0   17
4      0.713442    0   20
5      0.756347    0   27
6      0.782885    0  103
7      0.782685    0   25
8      0.757414    0   13
9      0.739978    0   15
10     0.731373    0   19
11     0.775287    0   47
12     0.765658    0   35

Sorting

In [11]:
dataset.groupby('state')['tot_victim'].sum().sort_values(ascending = False)

state
Illinois                16923
California              13206
Texas                   11152
Florida                 10981
Ohio                     8211
Pennsylvania             7451
North Carolina           6854
New York                 6764
Louisiana                6577
Georgia                  6512
Tennessee                6302
Missouri                 5721
Virginia                 5025
Alabama                  4878
Maryland                 4858
South Carolina           4694
Michigan                 4578
Indiana                  4564
New Jersey               3708
Mississippi              3059
Wisconsin                2979
Kentucky                 2960
Oklahoma                 2491
Arizona                  2190
Massachusetts            2173
Washington               2140
Arkansas                 2120
Colorado                 1929
District of Columbia     1874
Nevada                   1750
Connecticut              1599
Kansas                   1473
Minnesota                1377
Oregon                   1140
Iowa                     1094
Delaware                 1070
New Mexico               1038
West Virginia             984
Nebraska                  899
Utah                      684
Alaska                    592
Rhode Island              409
Idaho                     315
Montana                   290
Maine                     244
New Hampshire             232
South Dakota              204
North Dakota              199
Hawaii                    148
Vermont                   130
Wyoming                   125
Name: tot_victim, dtype: int64

In [12]:
dataset.groupby('month')['tot_victim'].count().sort_values(ascending = True)

month
11    17974
12    18106
4     18628
6     18755
2     18841
9     19656
10    19890
5     19930
8     21040
7     21126
3     22640
1     23091
Name: tot_victim, dtype: int64