In [1]:
import pandas as pd
import numpy as np

In [2]:
np.random.seed(100)

In [3]:
dff = pd.DataFrame(10*np.random.randn(10,3))
dff

           0          1          2
0 -17.497655   3.426804  11.530358
1  -2.524360   9.813208   5.142188
2   2.211797 -10.700433  -1.894958
3   2.550014  -4.580270   4.351635
4  -5.835951   8.168471   6.727208
5  -1.044111  -5.312804  10.297327
6  -4.381356 -11.183182  16.189817
7  15.416052  -2.518791  -8.424357
8   1.845187   9.370822   7.310003
9  13.615561  -3.262381   0.556760

In [4]:
# let we make missing
#dff.iloc[row,col] = np.nan
dff.iloc[3:5,0] = np.nan
dff.iloc[4:6,1] = np.nan
dff.iloc[5:8,2] = np.nan

dff

           0          1          2
0 -17.497655   3.426804  11.530358
1  -2.524360   9.813208   5.142188
2   2.211797 -10.700433  -1.894958
3        NaN  -4.580270   4.351635
4        NaN        NaN   6.727208
5  -1.044111        NaN        NaN
6  -4.381356 -11.183182        NaN
7  15.416052  -2.518791        NaN
8   1.845187   9.370822   7.310003
9  13.615561  -3.262381   0.556760

In [5]:
new_dff = dff.fillna(dff.mean())
new_dff

           0          1          2
0 -17.497655   3.426804  11.530358
1  -2.524360   9.813208   5.142188
2   2.211797 -10.700433  -1.894958
3   0.955139  -4.580270   4.351635
4   0.955139  -1.204278   6.727208
5  -1.044111  -1.204278   4.817599
6  -4.381356 -11.183182   4.817599
7  15.416052  -2.518791   4.817599
8   1.845187   9.370822   7.310003
9  13.615561  -3.262381   0.556760

In [6]:
third = dff.interpolate()
third

           0          1          2
0 -17.497655   3.426804  11.530358
1  -2.524360   9.813208   5.142188
2   2.211797 -10.700433  -1.894958
3   1.126494  -4.580270   4.351635
4   0.041191  -6.781241   6.727208
5  -1.044111  -8.982212   6.872907
6  -4.381356 -11.183182   7.018606
7  15.416052  -2.518791   7.164305
8   1.845187   9.370822   7.310003
9  13.615561  -3.262381   0.556760